# Generated by Django 5.1.7 on 2025-04-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
